### ISSUE TITLE
grep: ^https?:: No such file or directory

### ISSUE THREAD

**Issue by 0xWDG** [mrackwitz/Jeroboam#1]
```
* Sequel Pro.app
  Version: 1.1
  Sparkle Version: '1.5 Beta (bzr)'
  Feed URL: http://www.sequelpro.com/appcast/app-releases.xml
  ✗ ATS is not active
  ✗ Uses an insecure Feed URL
grep: ^https?:: No such file or directory
  Risk classification: IMMINENT DANGER
```

**Comment by mrackwitz** [comment]
Grep should be usually able to automatically determine that it should operate on stdin. Do you have a custom grep in your `$PATH`? Can you show me the output of `grep --version` and `which grep`?

**Comment by 0xWDG** [comment]
grep -V

```
grep -V
grep (BSD grep) 2.5.1-FreeBSD
```

$PATH

```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

which grep

```
which grep
/usr/bin/grep
```

OS X Info
    ~ system_profiler SPSoftwareDataType

```
Software:

System Software Overview:

  System Version: OS X 10.11.4 (15E39d)
  Kernel Version: Darwin 15.4.0
  Boot Volume: Macintosh HD
  Boot Mode: Normal
  Computer Name: MBP
  User Name: Wesley de Groot (wdg)
  Secure Virtual Memory: Enabled
  System Integrity Protection: Enabled
  Time since boot: 3 days 2:55
```

**Comment by mrackwitz** [comment]
Thanks for providing all these outputs. :+1:
Unfortunately I can't recognize a reason, why that should fail for you, while it works for me with the same versions. But actually this check shouldn't run at all specifically where it has occurred for you, so I fixed that instead in 3f5a07e.

I'll close that for now, if that should occur again (or for anyone else), please feel free to reopen / comment on it and provide more info to act on.

**Comment by 0xWDG** [comment]
Problem found.

it was a defined grep option

```
export GREP_OPTIONS="–-color=auto"
```

will kill this script.

```
PHPFramework$ echo "aaabbbxcccddd" | grep –-color=auto "x"
grep: x: No such file or directory
```

and

```
echo "aaabbbxcccddd" | grep "x"
aaabbbxcccddd
```

**Comment by mrackwitz** [comment]
Oh, wow. This is tricky. Thanks for reporting back.
